### PR TITLE
ci(macos): fix linker error

### PR DESCRIPTION
**Pull request by TheLostLambda**

### CODE REVIEW

**Comment by twop** [comment]
it seems that lld is not found(at least that is my interpretation of the CI error), I wonder if nee to be explicitly installed

**Comment by TheLostLambda** [comment]
@twop Indeed — hard coding the path to Rust's bundled one works for CI, but obviously not for local machines. I'll look into installing it in the CI!

**Comment by TheLostLambda** [comment]
@twop I think this is ready to go!

Let me know what you think of the solution and, importantly, if this fixes things on your local machine and closes #11

Thanks for pointing out that it was a doctest — that's why the `linker` settings weren't being respected!

**Comment by TheLostLambda** [comment]
@twop Merging and closing #11

Let me know if that should be reopened, and I hope to look at your PR in the next couple of days!

**Pull request merged**
